name: CI/CD Pipeline with MLflow and EC2 Deployment

on:
  push:
    branches:
      - main  # Branche sur laquelle vous souhaitez déployer

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliser Ubuntu comme environnement pour le runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Vérifie le code du dépôt

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # La version de Python que vous utilisez

    - name: Install dependencies
      run: |
        pip install --upgrade pip  # Mettre à jour pip pour éviter les problèmes de version
        pip install -r requirements.txt  # Installe toutes les dépendances du fichier requirements.txt

    - name: Run MLflow experiment
      run: |
        python scripts/train_model.py  # Exécutez le script d’entraînement du modèle et d’expérimentation avec MLflow

    - name: Deploy to EC2
      run: |
        ssh -i ${{ secrets.EC2_KEY }} ec2-user@${{ secrets.EC2_IP }} 'cd /path/to/app && git pull origin main && systemctl restart fastapi-app'
      env:
        EC2_IP: ${{ secrets.EC2_IP }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
